version: '2'
services:
  node-static-render:
    image: quay.io/d3lirium/node-static-render:latest
    depends_on:
      - 'pmp-fe-redis'
    environment:
      - DEBUG=nightmare
      - PORT=9000
      - NODE_REDIS_ENABLED=true
      - NODE_REDIS_HOST=pmp-fe-redis
      - NODE_ENV=production
    networks:
      - pmp-fe-network
    ports:
      - '9000:9000'
    restart: always
  pmp-fe-preact:
    build: ./pmp-fe-preact
    depends_on:
      - pmp-fe-api
      - node-static-render
    networks:
      - pmp-fe-network
    ports:
      - '80:80'
    restart: always
  pmp-fe-api:
    build: ./pmp-fe-api
    environment:
      - NODE_ENV=development
      - 'NODE_PMP_MONGODB_URI=mongodb://pmp-db:27017/pmp'
      - NODE_WINSTON_FILENAME=/logs/pmp_fe_api.log
      - PMP_REDIS_HOST=pmp-fe-redis
      - PORT=3000
    depends_on:
      - 'pmp-fe-redis'
      - 'pmp-db'
    networks:
      - pmp-fe-network
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./logs:/logs
  pmp-db:
    image: mongo:latest
    networks:
      - pmp-fe-network
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - db-volume:/data/db
  pmp-fe-redis:
    environment:
      - REDIS_MAXMEMORY=256mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    image: 'redis:latest'
    networks:
      - pmp-fe-network
    ports:
      - '6379:6379'
    restart: always
networks:
  pmp-fe-network:
    driver: bridge
volumes:
  db-volume: {}